apiVersion: v1
kind: Service
metadata:
  name: flyfox-worker
  namespace: flyfox
  labels:
    app: flyfox-worker
    component: worker
    tier: worker
spec:
  selector:
    app: flyfox-worker
  ports:
    - name: quantum-metrics
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: calling-metrics
      port: 9001
      targetPort: 9001
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: flyfox-quantum-worker
  namespace: flyfox
  labels:
    app: flyfox-worker
    component: quantum-worker
    tier: worker
spec:
  selector:
    app: flyfox-worker
  ports:
    - name: metrics
      port: 9000
      targetPort: 9000
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: flyfox-calling-worker
  namespace: flyfox
  labels:
    app: flyfox-worker
    component: calling-worker
    tier: worker
spec:
  selector:
    app: flyfox-worker
  ports:
    - name: metrics
      port: 9001
      targetPort: 9001
      protocol: TCP
  type: ClusterIP