# NQBA Platform - Production Secrets Template
# This file serves as a template for creating Kubernetes secrets
# DO NOT commit actual secrets to version control

apiVersion: v1
kind: Secret
metadata:
  name: nqba-platform-secrets
  namespace: nqba-platform
  labels:
    app: nqba-platform
    component: secrets
    environment: production
  annotations:
    kubernetes.io/description: "NQBA Platform production secrets"
type: Opaque
data:
  # Core Application Secrets (base64 encoded)
  SECRET_KEY: "<BASE64_ENCODED_SECRET_KEY>"
  JWT_SECRET_KEY: "<BASE64_ENCODED_JWT_SECRET_KEY>"
  ENCRYPTION_KEY: "<BASE64_ENCODED_ENCRYPTION_KEY>"
  
  # Database Configuration
  DATABASE_URL: "<BASE64_ENCODED_DATABASE_URL>"
  DATABASE_PASSWORD: "<BASE64_ENCODED_DB_PASSWORD>"
  
  # Redis Configuration
  REDIS_URL: "<BASE64_ENCODED_REDIS_URL>"
  REDIS_PASSWORD: "<BASE64_ENCODED_REDIS_PASSWORD>"
  
  # Quantum Computing APIs
  DYNEX_API_KEY: "<BASE64_ENCODED_DYNEX_API_KEY>"
  
  # AI/ML APIs
  OPENAI_API_KEY: "<BASE64_ENCODED_OPENAI_API_KEY>"
  
  # Business Integration APIs
  FLYFOX_API_KEY: "<BASE64_ENCODED_FLYFOX_API_KEY>"
  SIGMA_SELECT_API_KEY: "<BASE64_ENCODED_SIGMA_SELECT_API_KEY>"
  GOLIATH_TRADE_API_KEY: "<BASE64_ENCODED_GOLIATH_TRADE_API_KEY>"
  
  # AWS Services
  AWS_ACCESS_KEY_ID: "<BASE64_ENCODED_AWS_ACCESS_KEY_ID>"
  AWS_SECRET_ACCESS_KEY: "<BASE64_ENCODED_AWS_SECRET_ACCESS_KEY>"
  AWS_KMS_KEY_ID: "<BASE64_ENCODED_AWS_KMS_KEY_ID>"
  AWS_S3_BUCKET: "<BASE64_ENCODED_AWS_S3_BUCKET>"
  
  # Monitoring & Observability
  JAEGER_ENDPOINT: "<BASE64_ENCODED_JAEGER_ENDPOINT>"
  CLOUDFRONT_DOMAIN: "<BASE64_ENCODED_CLOUDFRONT_DOMAIN>"

---
# TLS Certificate Secret
apiVersion: v1
kind: Secret
metadata:
  name: nqba-platform-tls
  namespace: nqba-platform
  labels:
    app: nqba-platform
    component: tls
    environment: production
type: kubernetes.io/tls
data:
  tls.crt: "<BASE64_ENCODED_TLS_CERTIFICATE>"
  tls.key: "<BASE64_ENCODED_TLS_PRIVATE_KEY>"

---
# Docker Registry Secret
apiVersion: v1
kind: Secret
metadata:
  name: nqba-platform-registry
  namespace: nqba-platform
  labels:
    app: nqba-platform
    component: registry
    environment: production
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "<BASE64_ENCODED_DOCKER_CONFIG_JSON>"

---
# Service Account for NQBA Platform
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nqba-api
  namespace: nqba-platform
  labels:
    app: nqba-platform
    component: service-account
    environment: production
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::<ACCOUNT_ID>:role/nqba-platform-service-role"
imagePullSecrets:
- name: nqba-platform-registry
secrets:
- name: nqba-platform-secrets

---
# ConfigMap for non-sensitive configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: nqba-platform-config
  namespace: nqba-platform
  labels:
    app: nqba-platform
    component: config
    environment: production
data:
  ENVIRONMENT: "production"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  WORKERS: "4"
  
  # CORS Configuration
  CORS_ORIGINS: "https://app.flyfox.ai,https://api.flyfox.ai"
  CORS_ALLOW_CREDENTIALS: "true"
  CORS_ALLOW_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_ALLOW_HEADERS: "*"
  
  # Rate Limiting
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS_PER_MINUTE: "100"
  RATE_LIMIT_BURST: "20"
  
  # Database Configuration (non-sensitive)
  DATABASE_POOL_SIZE: "20"
  DATABASE_MAX_OVERFLOW: "30"
  DATABASE_POOL_TIMEOUT: "30"
  DATABASE_POOL_RECYCLE: "3600"
  DATABASE_SSL_MODE: "require"
  DB_RETRY_ATTEMPTS: "3"
  DB_RETRY_DELAY: "1"
  
  # Redis Configuration (non-sensitive)
  REDIS_POOL_SIZE: "20"
  REDIS_TIMEOUT: "5"
  REDIS_RETRY_ON_TIMEOUT: "true"
  REDIS_HEALTH_CHECK_INTERVAL: "30"
  
  # Quantum Computing Settings
  DYNEX_API_URL: "https://api.dynexcoin.org"
  DYNEX_TIMEOUT: "300"
  DYNEX_MAX_RETRIES: "3"
  DYNEX_RETRY_DELAY: "5"
  QUANTUM_MAX_QUBITS: "50"
  QUANTUM_MAX_CIRCUIT_DEPTH: "1000"
  QUANTUM_TIMEOUT: "600"
  
  # AI/ML Configuration
  OPENAI_MODEL: "gpt-4"
  OPENAI_MAX_TOKENS: "4000"
  OPENAI_TEMPERATURE: "0.7"
  OPENAI_TIMEOUT: "60"
  MODEL_CACHE_TTL: "3600"
  MODEL_CACHE_SIZE: "1000"
  
  # Monitoring & Observability
  METRICS_ENABLED: "true"
  METRICS_PORT: "9090"
  METRICS_PATH: "/metrics"
  LOG_ROTATION: "true"
  LOG_MAX_SIZE: "100MB"
  LOG_BACKUP_COUNT: "10"
  LOG_COMPRESSION: "true"
  TRACING_ENABLED: "true"
  TRACING_SAMPLE_RATE: "0.1"
  HEALTH_CHECK_INTERVAL: "30"
  HEALTH_CHECK_TIMEOUT: "10"
  HEALTH_CHECK_RETRIES: "3"
  
  # Security & Compliance
  AUDIT_LOG_ENABLED: "true"
  AUDIT_LOG_LEVEL: "INFO"
  AUDIT_RETENTION_DAYS: "2555"
  ENCRYPTION_AT_REST: "true"
  ENCRYPTION_IN_TRANSIT: "true"
  ENCRYPTION_ALGORITHM: "AES-256-GCM"
  KMS_PROVIDER: "aws"
  KEY_ROTATION_ENABLED: "true"
  KEY_ROTATION_INTERVAL: "90"
  GDPR_ENABLED: "true"
  CCPA_ENABLED: "true"
  SOC2_COMPLIANCE: "true"
  DATA_RESIDENCY: "US"
  
  # Performance Settings
  CACHE_ENABLED: "true"
  CACHE_TTL: "3600"
  CACHE_MAX_SIZE: "1000"
  HTTP_POOL_SIZE: "100"
  HTTP_POOL_TIMEOUT: "30"
  HTTP_KEEP_ALIVE: "true"
  
  # Celery Configuration
  CELERY_TASK_SERIALIZER: "json"
  CELERY_RESULT_SERIALIZER: "json"
  CELERY_TIMEZONE: "UTC"
  CELERY_WORKER_CONCURRENCY: "4"
  
  # Business Integration URLs
  FLYFOX_API_URL: "https://api.flyfox.ai"
  SIGMA_SELECT_API_URL: "https://api.sigmaselect.com"
  GOLIATH_TRADE_API_URL: "https://api.goliath.trade"
  
  # External Services
  EMAIL_PROVIDER: "aws-ses"
  EMAIL_FROM_ADDRESS: "noreply@flyfox.ai"
  EMAIL_REGION: "us-west-2"
  STORAGE_PROVIDER: "aws-s3"
  STORAGE_REGION: "us-west-2"
  STORAGE_ENCRYPTION: "true"
  CDN_ENABLED: "true"
  
  # Container Settings
  CONTAINER_PORT: "8000"
  CONTAINER_WORKERS: "4"
  CONTAINER_TIMEOUT: "300"
  CONTAINER_KEEP_ALIVE: "2"
  
  # Kubernetes
  KUBERNETES_NAMESPACE: "nqba-platform"
  KUBERNETES_SERVICE_ACCOUNT: "nqba-api"
  
  # Load Balancer
  LOAD_BALANCER_TIMEOUT: "60"
  LOAD_BALANCER_HEALTH_CHECK: "/health"
  LOAD_BALANCER_HEALTH_CHECK_INTERVAL: "30"
  
  # Auto Scaling
  AUTO_SCALING_ENABLED: "true"
  AUTO_SCALING_MIN_REPLICAS: "3"
  AUTO_SCALING_MAX_REPLICAS: "20"
  AUTO_SCALING_TARGET_CPU: "70"
  AUTO_SCALING_TARGET_MEMORY: "80"
  
  # Backup & Disaster Recovery
  BACKUP_ENABLED: "true"
  BACKUP_SCHEDULE: "0 2 * * *"
  BACKUP_RETENTION_DAYS: "30"
  BACKUP_ENCRYPTION: "true"
  PITR_ENABLED: "true"
  PITR_RETENTION_DAYS: "7"
  CROSS_REGION_BACKUP: "true"
  BACKUP_REGION: "us-east-1"