services:
  # Partner API Backend
  partner-api:
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://partner_user:partner_pass@partner-db:5432/partner_db
    depends_on:
      - partner-db
    volumes:
      - ../api:/app
    networks:
      - partner-network

  # Partner Portal Frontend
  partner-portal:
    build:
      context: ../ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - partner-api
    networks:
      - partner-network

  # PostgreSQL Database
  partner-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=partner_db
      - POSTGRES_USER=partner_user
      - POSTGRES_PASSWORD=partner_pass
    ports:
      - "5433:5432"
    volumes:
      - partner-db-data:/var/lib/postgresql/data
    networks:
      - partner-network

volumes:
  partner-db-data:

networks:
  partner-network:
    driver: bridge
