apiVersion: apps/v1
kind: Deployment
metadata:
  name: partner-portal
  namespace: partner-system
  labels:
    app: partner-portal
    component: frontend
    phase: phase1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: partner-portal
  template:
    metadata:
      labels:
        app: partner-portal
        component: frontend
        phase: phase1
    spec:
      containers:
      - name: partner-portal
        image: goliath-partner-portal:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: partner-system-config
              key: ENVIRONMENT
        - name: PORTAL_HOST
          valueFrom:
            configMapKeyRef:
              name: partner-system-config
              key: PORTAL_HOST
        - name: PORTAL_PORT
          valueFrom:
            configMapKeyRef:
              name: partner-system-config
              key: PORTAL_PORT
        - name: REACT_APP_API_URL
          value: "http://partner-api:8080"
        - name: REACT_APP_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: partner-system-config
              key: ENVIRONMENT
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
      securityContext:
        fsGroup: 1000
